platform:
  - x64
environment:
  matrix:
    - MSYS2_ARCH: x86_64
install:
  - C:\\msys64\usr\bin\bash -lc ""
  - C:\\msys64\usr\bin\bash -lc "for i in {1..3}; do pacman --noconfirm -Suy mingw-w64-%MSYS2_ARCH%-{enchant} && break || sleep 15; done"