platform:
  - x64
environment:
  MINGW_INSTALLS: mingw64
install:
  - C:\msys64\usr\bin\bash -lc ""
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Suy"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-hunspell mingw-w64-i686-hunspell"
#  - C:\msys64\usr\bin\bash -lc "find /mingw64/lib -name '*.dll.a' -exec rm {} \\;"
  - C:\Python35-x64\python.exe -m pip install wheel
build_script:
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/tools/mingw-w64-enchant; exec 0</dev/null; makepkg-mingw"
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/tools/mingw-w64-enchant/build; mkdir -p lib/enchant"
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/tools/mingw-w64-enchant; cp src/enchant-1.6.0-build-x86_64/src/.libs/libenchant.dll build/lib/"
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/tools/mingw-w64-enchant; cp src/enchant-1.6.0-build-x86_64/src/ispell/.libs/libenchant_ispell.dll build/lib/enchant/"
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/tools/mingw-w64-enchant; cp src/enchant-1.6.0-build-x86_64/src/myspell/.libs/libenchant_myspell.dll build/lib/enchant/"
  - C:\Python35-x64\python.exe setup.py build
#test_script:
#  - C:\Python35-x64\python.exe setup.py test
#after_test:
#  - C:\Python35-x64\python.exe setup.py bdist_wheel
artifacts:
  - path: tools/mingw-w64-enchant
  - path: dist