init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
platform:
  - x64
matrix:
  allow_failures:
    - platform: x64
environment:
  MINGW_INSTALLS: mingw64
install:
  - C:\msys64\usr\bin\bash -lc ""
#  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Suy"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-hunspell"
#  - C:\msys64\usr\bin\bash -lc "find /mingw64/lib -name '*.dll.a' -exec rm {} \\;"
  - C:\Python35-x64\python.exe -m pip install wheel
build_script:
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/tools/mingw-w64-enchant; exec 0</dev/null; makepkg-mingw"
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/tools/mingw-w64-enchant/build; mkdir -p lib/enchant"
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/tools/mingw-w64-enchant; cp src/build-x86_64*/src/.libs/libenchant.dll build/lib/"
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/tools/mingw-w64-enchant; cp src/build-x86_64*/src/ispell/.libs/libenchant_ispell.dll build/lib/enchant/"
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/tools/mingw-w64-enchant; cp src/build-x86_64*/src/myspell/.libs/libenchant_myspell.dll build/lib/enchant/"
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/tools/mingw-w64-enchant; cp /mingw64/bin/libglib-2.0-0.dll build/lib/"
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/tools/mingw-w64-enchant; cp /mingw64/bin/libgmodule-2.0-0.dll build/lib/"
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/tools/mingw-w64-enchant; cp /mingw64/bin/libintl-8.dll build/lib/"
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/tools/mingw-w64-enchant; cp /mingw64/bin/libiconv-2.dll build/lib/"
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/tools/mingw-w64-enchant; cp /mingw64/bin/libwinpthread-1.dll build/lib/"
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/tools/mingw-w64-enchant; cp /mingw64/bin/libgcc_s_seh-1.dll build/lib/"
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/tools/mingw-w64-enchant; cp /mingw64/bin/libstdc++-6.dll build/lib/"
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/tools/mingw-w64-enchant/build/share/enchant/myspell; for file in *.zip; do unzip -l $file; done"
test_script:
  - C:\Python35-x64\python.exe setup.py build
  - C:\Python35-x64\python.exe setup.py test
#after_test:
#  - C:\Python35-x64\python.exe setup.py bdist_wheel
artifacts:
  - path: tools/mingw-w64-enchant
#  - path: dist