platform:
  - x86
environment:
  matrix:
    - MSYS2_ARCH: i686
install:
  - C:\msys64\usr\bin\bash -lc ""
  - C:\msys64\usr\bin\bash -lc "for i in {1..3}; do pacman --noconfirm -Suy mingw-w64-%MSYS2_ARCH%-glib2 mingw-w64-%MSYS2_ARCH%-pkg-config && break || sleep 15; done"
  - git clone https://github.com/AbiWord/enchant.git C:\projects\enchant
build_script:
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/../enchant; PATH=$PATH:/mingw32/bin; PKG_CONFIG="/mingw32/bin/pkg-config"; ./autogen.sh; make"
artifacts:
  - path: C:\projects\enchant