platform:
  - x86
environment:
  matrix:
    - MSYS2_ARCH: i686
install:
  - C:\msys64\usr\bin\bash -lc ""
  - C:\msys64\usr\bin\bash -lc "for i in {1..3}; do pacman --noconfirm -Suy mingw-w64-%MSYS2_ARCH%-glib2 mingw-w64-%MSYS2_ARCH%-pkg-config && break || sleep 15; done"
build_script:
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/tools/pyenchant-bdist-win32-sources; PATH=/mingw32/bin:$PATH; make"
artifacts:
  - path: tools\pyenchant-bdist-win32-sources