platform:
  - x86
environment:
  matrix:
    - MSYS2_ARCH: i686
install:
  - C:\msys64\usr\bin\bash -lc ""
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Suy"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-%MSYS2_ARCH%-glib2 mingw-w64-%MSYS2_ARCH%-pkg-config"
  - C:\msys64\usr\bin\bash -lc "git clone https://github.com/msys2/MINGW-packages.git $APPVEYOR_BUILD_FOLDER/../MINGW-packages"
build_script:
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/../MINGW-packages/mingw-w64-enchant; makepkg-mingw"
artifacts:
  - path: MINGW-packages\mingw-w64-enchant