platform:
  - x64
install:
  - C:\msys64\usr\bin\bash -lc ""
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Suy"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-hunspell mingw-w64-i686-hunspell"
  - C:\msys64\usr\bin\bash -lc "git clone https://github.com/msys2/MINGW-packages.git $APPVEYOR_BUILD_FOLDER/../MINGW-packages"
build_script:
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/../MINGW-packages/mingw-w64-enchant; perl -i".bak" -pe "s/^test -n \".DJDIR\"/#$&/" configure; makepkg-mingw"
artifacts:
  - path: MINGW-packages\mingw-w64-enchant